### PR TITLE
CentOS 8 is EOL since 31/12/2021

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes https://github.com/ocurrent/docker-base-images/issues/157

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
https://www.centos.org/centos-linux-eol/

**Comment by dra27** [comment]
I haven't looked at the detail, but shouldn't we rather be switching to CentOS Stream?

**Comment by dra27** [comment]
It feels very strange to me for the centos-latest tag to go backwards. There are some possibilities (we could do several of them):
- Use the Quay Container Registry for the base image (`quay.io/centos/centos:stream8`)
- Add RedHat Base Images (Docker Hub - [redhat/ubi8](https://hub.docker.com/r/redhat/ubi8) or [redhat/ubi8-minimal](https://hub.docker.com/r/redhat/ubi8-minimal)if we can build with that)
- Add Rocky Linux (and possibly even point the centos-latest tag to that?!)
- Stop updating the centos-latest tag

**Comment by dra27** [comment]
In terms of right now, because we certainly need to get CentOS 8 out of the distros list, given that it can't even update, would it be OK to restore the alias of `` `CentOS `Latest`` to point to `` `V8`` but _remove_ `` `CentOS `Latest` from both `Dockerfile_distro.distros` and `Dockerfile_distro.latest_distros`. Certainly on the base image builder that stops it from pushing `ocaml/opam:centos-*` images for now which means that they're simply out-of-date as opposed to suddenly jumping back to CentOS 7. Then we can decide with less pressure on what to do (if anything, eventually) about CentOS/RHEL/Rocky

**Comment by kit-ty-kate** [comment]
I’m not sure leaving `` `CentOS `Latest`` to point to `` `V8`` is the right thing to do. For example other distributions such as Debian have their `` `Latest`` pointing to the "latest stable" (11 currently) instead of "latest latest" (11 or sid).

To me 7 is their currently available "latest stable" version at the moment.

**Comment by dra27** [comment]
Heh, heh - other distributions don't stop support for version _N_ **before** version _N-1_ 🙂 I guess you're right - it's seriously weird, but so's having `ocaml/opam:centos-ocaml-*` being old and out-of-date. I guess I'll have to hold my nose!

**Comment by tmcgilchrist** [comment]
> Add Rocky Linux 
Seems like the most like for like replacement for CentOS.

**Comment by dra27** [comment]
Nose held! 🙂

**Pull request merged**
