### PR TITLE
Fix the group creation of the opam user

### PR DESCRIPTION
**Pull request by kit-ty-kate**
-g means GECOS whereas -G means group

Issue observed in https://github.com/ocaml/opam-repository/pull/17882

### CODE REVIEW

**Comment by avsm** [comment]
good catch!

**Review by avsm — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Should be good to go now.

Btw are there any news about the move to the `ocurrent` org for this repo?

**Comment by jrochel** [comment]
No worries. Glad I could be of help. Another version of ocsigenserver is coming up soon.

**Comment by avsm** [comment]
This PR breaks the build in docker-base-images. Investigating...

```
addgroup: group 'opam' in use
The command '/bin/sh -c addgroup -S -g 1000 opam' returned a non-zero code: 1
```

**Comment by avsm** [comment]
fixed in c916c7ea8a8b3deb5eda53babeb130ec5f88cc1d

**Comment by kit-ty-kate** [comment]
Sorry about that

**Pull request merged**
