### PR TITLE
Upgrade to debian-11

### PR DESCRIPTION
**Pull request by kit-ty-kate**
debian 11 was released a few hours ago

### CODE REVIEW

**Comment by talex5** [comment]
Doesn't compile. Did you forget to commit a change?

I think the process then is to open a PR at https://github.com/ocurrent/docker-base-images updating to this version to test it further.

**Comment by kit-ty-kate** [comment]
CI is green now

**Comment by dra27** [comment]
LGTM - can you open a test PR for it on docker-base-images and assume deployability passes I can push that to live at the same time as the August Windows LCU and test them both on just one run.

**Comment by kit-ty-kate** [comment]
Done in https://github.com/ocurrent/docker-base-images/pull/128. This both include your changes in master and mine.

**Comment by dra27** [comment]
That all seems to be working - good to merge, @avsm?

**Pull request merged**
