### PR TITLE
Setup opam wrappers in created dockers

### PR DESCRIPTION
**Pull request by AltGr**
This should take the wrappers in `<opam_source>/shell/wrap-*.sh`, when they
exist (newer opams only) install them and set them up for the new opam.

This will enforce Linux namespaces upon building and installing the packages,
preventing them from doing network access when they shouldn't, writing files
where they shouldn't, etc.

NOTE 1: this is untested (but the namespace wrappers are)

NOTE 2: some current compiler definitions (e.g. 
https://github.com/ocaml/opam-repository/blob/master/compilers/4.03.0/4.03.0/4.03.0.comp) 
are broken, according to opam rules, and won't pass this. They need fixing,
i.e. not write to PREFIX before `make install`.

### CODE REVIEW

**Comment by AltGr** [comment]
Ping ?

**Comment by avsm** [comment]
Sorry about the delay -- I'm rebuilding all the containers with this change and will update here when they're active.

**Comment by AltGr** [comment]
Be aware that note 2 above may break a lot of compilers, if not fixed

**Comment by avsm** [comment]
I think that's ok for the containers -- we don't really test the compilers at the moment in CI, so this is a good excuse to break them and then fix them. I dont think it'll regress anything.

**Comment by avsm** [comment]
Also it will only break the OPAM2 ones, which aren't something anyone is depending on that I know of.

**Comment by avsm** [comment]
This is deployed now in ocaml/opam-dev, but the rc file is not enabled by default as it requires a privileged container to work by default. I've filed https://github.com/ocaml/opam/issues/2917 as the feature request to make it easier to activate these sandboxes in the Docker-based CI.

**Pull request merged**
